---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::438723512299:role/irsa-alb-ingress-remediation-lab-dev
    eks.amazonaws.com/sts-regional-endpoints: "true"
