---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-09-08T05:33:21Z"
  name: argocd-manager
  namespace: kube-system
  resourceVersion: "6021846"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/argocd-manager
  uid: 58e30d66-70de-42a8-beb3-b063c793d7af
secrets:
- name: argocd-manager-token-466gl
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd-manager-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argocd-manager-role
subjects:
- kind: ServiceAccount
  name: argocd-manager
  namespace: kube-system
