apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-dex-server
  
spec:
  template:
    spec:
      nodeSelector:
        mine/group: default  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  
spec:
  template:
    spec:
      nodeSelector:
        mine/group: default  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  
spec:
  template:
    spec:
      nodeSelector:
        mine/group: default  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
  
spec:
  template:
    spec:
      nodeSelector:
        mine/group: default
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: argocd-application-controller
spec:
  template:
    spec:
      containers:
      - name: argocd-application-controller
        resources:
          limits:
            cpu: 1200m
            memory: 600Mi
          requests:
            cpu: 800m
            memory: 300Mi
