apiVersion: v1
kind: Secret
metadata:
  name: my-private-repo
  
  labels:
    app.kubernetes.io/name: my-private-repo
    argocd.argoproj.io/secret-type: repository
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  password: your-git-personal-access-token # FIXME
  url: aHR0cHM6Ly9naXRodWIuY29tL2RhdHRvbjk0L3JlbWVkaWF0aW9uLWxhYg==
  username: ZGF0dG9uOTQ=
